### ISSUE TITLE
分别运行所有task的test都是passed，但是运行testAll.py时有时OK，有时报错，报错时的信息如下：（报错发生位置不固定，Error原因都是远程主机强迫关闭了一个现有的连接）

### ISSUE THREAD

**Issue by TonyZhang14242** [yuk1i/cs305-2022fall-homework1-student#4]
ERROR: test02TestGetImage (tests.TestTask5Cookie.TestTask5Cookie)

Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    yield
  File "D:\anaconda3\lib\site-packages\urllib3\response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "D:\anaconda3\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "D:\anaconda3\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "D:\anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\requests\models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "D:\anaconda3\lib\site-packages\urllib3\response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\anaconda3\lib\site-packages\urllib3\response.py", line 544, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "D:\anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\anaconda3\lib\site-packages\urllib3\response.py", line 458, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\HTTP_Server\tests\TestTask5Cookie.py", line 16, in test02TestGetImage
    resp = s.post(self.server_base + "api/login", json={"username": "admin", "password": "admin"})
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\lib\site-packages\requests\sessions.py", line 687, in send
    r.content
  File "D:\anaconda3\lib\site-packages\requests\models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "D:\anaconda3\lib\site-packages\requests\models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

----------------------------------------------------------------------
Ran 11 tests in 0.365s

FAILED (errors=1)

**Comment by TonyZhang14242** [comment]
好像在socket.recv()前加上一个time.sleep(0.1)可以解决？
